### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by okonet** [okonet/react-dropzone#123]
Some ideas:
1. [x] Full body dropzone
2. [ ] Examples from README.md
3. [ ] Dynamic example with toggling different props

**Comment by simpixelated** [comment]
> full body dropzone

:astonished: that would be awesome! What would be the "right" way to do this in React? It looks like [react-modal (in `componentDidMount`) appends a new element to the bottom of the body](https://github.com/reactjs/react-modal/blob/master/lib/components/Modal.js#L43) which serves as the overlay. Could do something similar for `<Dropzone>`.

**Comment by okonet** [comment]
I wouldn't mind a PR if you feel like it :)

**Comment by simpixelated** [comment]
I started working on this, but I'm fairly new to React so I got stuck with implementation. Here's what I have so far: https://github.com/okonet/react-dropzone/compare/master...simpixelated:full-body

It works as a proof of concept: when `<Dropzone>` is mounted, it attaches listeners to the `document` and will render `<DropzonePortal>` at the bottom of the page, which gets displayed as an overlay on `dragenter` of the body.

The problem I'm running into is how to inherit/share all of the functionality of `Dropzone` without just straight copying and pasting. Plus, I'm not quite sure if the original Dropzone should still be used, or if DropzonePortal should instead inherit it's props and render it's children. Or is there a way to move/copy the `Dropzone` element to the body during a React lifecycle event, instead of using another component entirely (like DropzonePortal)?

Let me know if you have any suggestions. Thanks!

**Comment by okonet** [comment]
Related: https://github.com/okonet/react-dropzone/issues/143#issuecomment-190301457

**Comment by bogas04** [comment]
Can someone give an example of uploading using `fetch` API ?

**Comment by wvance** [comment]
If I understood the "full body dropzone right" I implemented it with React Redux by: 

1. Wrapping my entire app in the Dropzone component
2. Overwrote the inline styles by passing in an empty style object
3. Added a global Redux state to true when with onDragEnter was hit and false to when onDragLeave was called. 
4. Conditionally added a div in react using the global Redux state as described above. It works beautifully!

**Comment by okonet** [comment]
@wvance can you share the example with us? A gist or a PR against the README would be great! I also would like to include the gif as well.

**Comment by wvance** [comment]
Here's the gist, I'll do a PR on the README later as well. https://gist.github.com/wvance/c052a57654ea943edee113a180598ab8

**Comment by okonet** [comment]
@wvance waiting for the PR!

**Comment by okonet** [comment]
https://react-dropzone.js.org/
