### ISSUE TITLE
Dist package ?

### ISSUE THREAD

**Issue by hajime-moto** [okonet/react-dropzone#208]
It would be really helpful to have a dist folder for people who want to import the JS files directly into their project.

**Comment by okonet** [comment]
Although it's okay for quick prototypes I don't believe this is good for real projects and I want to discourage this. Why someone would like to have a browser version? What's the advantage here?

**Comment by hajime-moto** [comment]
It's for a Scala.js project. I'm using SBT to build the project and I'm not using webpack or browserify hence the reason for the dist package request :) 

I usually see a `dist` folder in all JS projects so I thought I should ask. But if it's not a good practice then I will try compile it locally with webpack.

**Comment by okonet** [comment]
I'm not sure I'm following. There is a `dist/index.js` but it doesn't work in the browser out of the box. Would this be enough for you or you want to make it UMD-compatible?

**Comment by AntiFish03** [comment]
A committed `dist/*` would be very helpful for people using bower with a non node backend (and not using `webpack` or `browserify`).

I checkout resources during deploy (instead of them being checked into the repo) the advantage is that no one gets the bright idea to change the vendor scripts, the downfall tends to be the attitude that you have
> Although it's okay for quick prototypes I don't believe this is good for real projects

and because I can't just go into the `react-dropzone` package folder and run `webpack` ( well I could but it would only run locally as it is never committed)

The idea behind this is a 3rd party library is not the primary purpose of a project it is a component, or utility and as such there is no reason that a 3rd parties code should be checked into the project repo.  Its a similar philosophy to Ruby and bundled gems or PHP and composer.

**Comment by okonet** [comment]
There is a dist in this package. You should use npm to install it. See README.md.
