### ISSUE TITLE
DataTransfer.items doesn't provide file name, it fails the styling when `accept` prop using extension

### ISSUE THREAD

**Issue by kl2735** [okonet/react-dropzone#215]
So in OnDragEnter, we use `DataTransfer.items` instead of `DataTransfer.files` cuz the second is empty array in that case. 

but in items, we don't have filename. So we will use type (mimeType) for validation for the styling (showing red border when hovering).

So if i pass `.mp4` to `accept` props. my styling for hovering a file is never gonna be right, cuz it uses mimeType to compare, instead of fileName (cuz we don't have file name at this moment)

While showing the invalid when hovering a file (OnDragEnter), onDrop can be valid, since we use `DataTransfer.files`, it has the file name. So for checking, `.mp4`  extension works well. 

that is a unmatch for styling and real reaction

**Comment by okonet** [comment]
I'm not sure what's this issue is about. Can you provide more information of what is the expected behavior and what are you seeing? Is this happening because of this library? Or some of your code? Best way would be to create a separate isolated GH repo with your case + description of what is going on.

**Comment by okonet** [comment]
I've just tried it in Chrome Canary and it worked fine with `.pdf`. Are you seeing in a specific browser?

**Comment by ValYouW** [comment]
Hi,

The problem arise when using file extension in the `accept` field instead of mime type.
If I have this: `<Dropzone accept=".svg,.jpg,.jpeg,.gif,.png">` and I drag a ".jpg" file, it will get **rejected** while dragging, but get **accepted** onDrop.
Reason:
onDragEnter event won't give us the file name while onDrop will give us the file name, and the attr-accept library supports both mime type and file extensions, so when validating onDragEnter it attr-accept will reject it, and when validating onDrop attr-accept will accept it - hence the inconsistency.
Don't think much can be done here which is a bummer... unless there is some way to get the file name onDragStart/Enter/Over

**Comment by okonet** [comment]
Thanks for clarification. You can't get the file name during the drag. As a workaround you should use mime-types instead.

**Comment by xsburg** [comment]
@okonet, I think it should be mentioned in the docs in the way it's noted about cross-platform MIME. In fact, the comment about MIME naturally steers you towards using file extensions in `accept` as the most reliable thing and then you just stumble upon this vague bug. It took me drilling down into the code to realize what the problem is.

**Comment by okonet** [comment]
I'm open for PRs to the documentation or even implementation for this if someone up to.

**Comment by okonet** [comment]
Related to #459 #477
