### ISSUE TITLE
Firefox 51.0.1  activates rejectStyle even on accepted file types.

### ISSUE THREAD

**Issue by releaf** [okonet/react-dropzone#362]
In Firefox 51.0.1, the dropzone initiates the rejectStyle even though a file is of the accepted type. The drop and upload still works fine but the UI indicates otherwise. 

![fire-fox-bug](https://cloud.githubusercontent.com/assets/4107042/23179641/93008344-f83c-11e6-9fe4-9e81034116ca.gif)

**Comment by okonet** [comment]
Looks like Firefox broke it. I believe it should be fixed in Firefox since it looks like they broke the HTML5 API. Fancy to submit a bug to them?

**Comment by releaf** [comment]
Hopefully this gets some traction. Please feel free to add some clarity around the issue if you can. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1342057

**Comment by mwolson** [comment]
None of the workarounds proposed in the Firefox bugtracker are any good, since they happen on a `drop()` event, and not on `dragEnter` events. Until they fix it upstream, we should at least make it look like all attachments are accepted while dragging, which brings us to parity with Safari (which doesn't support file types on drag items at all). A false positive is better than a false negative here. PR #382 implements this.
